import { PRINT_MONEY, PURCHASE_PRODUCT } from './actions';
import { ACTION_PRINT, ACTION_BUY } from './verify';
import { CORE_VERSION } from './version';

/**
 * Turns dispatched actions into replay-log entries.
 *
 * Only player actions are recorded, and only that they happened. Ticks are
 * regenerated by the verifier, and amounts come from replayed state, so there
 * is nothing here for a client to inflate.
 *
 * Recording is deliberately separate from the reducer: the log is evidence
 * about a session, not part of its state, and keeping it out means the core
 * stays a pure function of its inputs.
 */
export const createRecorder = ({ sessionId, startedAt }) => {
    const actions = [];

    return {
        /** Called with the action and the tick it happened on. */
        record(action, tick) {
            if (action.type === PRINT_MONEY) {
                actions.push([tick, ACTION_PRINT]);
            } else if (action.type === PURCHASE_PRODUCT) {
                actions.push([tick, ACTION_BUY, action.productName]);
            }
        },

        get length() {
            return actions.length;
        },

        toLog(submittedAt) {
            return {
                coreVersion: CORE_VERSION,
                sessionId,
                startedAt,
                submittedAt,
                actions: actions.slice()
            };
        }
    };
};

export default createRecorder;
