import { PRINT_MONEY, PURCHASE_PRODUCT, PURCHASE_UPGRADE } from './actions.js';
import { ACTION_PRINT, ACTION_BUY, ACTION_UPGRADE } from './verify.js';
import { CORE_VERSION } from './version.js';

/**
 * Turns dispatched actions into replay-log entries.
 *
 * Only player actions are recorded, and only that they happened. Ticks are
 * regenerated by the verifier, and amounts come from replayed state, so there
 * is nothing here for a client to inflate.
 *
 * Recording is deliberately separate from the reducer: the log is evidence
 * about a session, not part of its state, and keeping it out means the core
 * stays a pure function of its inputs.
 */
export const createRecorder = ({ sessionId, startedAt, actions: existing }) => {
    // Resuming carries the actions recorded before a reload. There is nothing
    // to protect here: the server replays the log, so a player who edits it
    // only changes what the rules will award them, which is nothing.
    const actions = Array.isArray(existing) ? existing.slice() : [];

    return {
        /** Called with the action and the tick it happened on. */
        record(action, tick) {
            if (action.type === PRINT_MONEY) {
                actions.push([tick, ACTION_PRINT]);
            } else if (action.type === PURCHASE_PRODUCT) {
                actions.push([tick, ACTION_BUY, action.productName]);
            } else if (action.type === PURCHASE_UPGRADE) {
                actions.push([tick, ACTION_UPGRADE, action.upgradeId]);
            }
        },

        get length() {
            return actions.length;
        },

        get sessionId() {
            return sessionId;
        },

        get startedAt() {
            return startedAt;
        },

        toLog(submittedAt) {
            return {
                coreVersion: CORE_VERSION,
                sessionId,
                startedAt,
                submittedAt,
                actions: actions.slice(),
            };
        },
    };
};

export default createRecorder;
